version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: payment_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: paymentuser
      POSTGRES_PASSWORD: paymentpass
      POSTGRES_DB: payment_db
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    ports:
      - "5432:5432"  # Expose to host for debugging
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paymentuser -d payment_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - payment_network

  # Payment Service
  payment_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment_service
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      # Database connection (note: use service name 'postgres' not 'localhost')
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: paymentuser
      DB_PASSWORD: paymentpass
      DB_NAME: payment_db
      DB_SSLMODE: disable
      # Service config
      SERVICE_PORT: 8082
      LOG_LEVEL: info
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - payment_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/health"]
      interval: 30s
      timeout: 3s
      start_period: 10s
      retries: 3

  # pgAdmin - Database GUI (optional, for development)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: payment_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@payment.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - payment_network
    profiles:
      - dev  # Only starts with --profile dev

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  payment_network:
    driver: bridge