version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: payment_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: paymentuser
      POSTGRES_PASSWORD: paymentpass
      POSTGRES_DB: payment_db
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paymentuser -d payment_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - payment_network

  # pgAdmin - Database GUI
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: payment_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@payment.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - payment_network
    profiles:
      - dev  

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  payment_network:
    driver: bridge