version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: payment_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: paymentuser
      POSTGRES_PASSWORD: paymentpass
      POSTGRES_DB: payment_db
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paymentuser -d payment_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - payment-network

  payment_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment_service
    restart: unless-stopped
    ports:
      - "8082:8082"
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24225
        tag: payment-service
        fluentd-async: "true"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: paymentuser
      DB_PASSWORD: paymentpass
      DB_NAME: payment_db
      DB_SSLMODE: disable
      SERVICE_PORT: 8082
      LOG_LEVEL: info
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - payment-network
      - microservices-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payment_svc.rule=PathPrefix(`/api/v1/payment_svc`)"
      - "traefik.http.routers.payment_svc.entrypoints=web,websecure"
      - "traefik.http.routers.payment_svc.priority=100"
      - "traefik.http.services.payment_svc.loadbalancer.server.port=8082"
      - "traefik.http.middlewares.payment_stripprefix.stripprefix.prefixes=/api/v1/payment_svc"
      - "traefik.http.routers.payment_svc.middlewares=payment_stripprefix"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/health"]
      interval: 30s
      timeout: 3s
      start_period: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  payment-network:
    driver: bridge
  microservices-network:
    external: true