version: '3.8'

services:
  # NGINX (API Gateway)
  gateway:
    image: nginx:stable-alpine
    container_name: nginx_gateway
    ports:
      - "8080:80"       
    volumes:
      - ~/go/oms-micro/api_gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      payment_service:
        condition: service_healthy
    networks:
      - payment_network
  
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: payment_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: paymentuser
      POSTGRES_PASSWORD: paymentpass
      POSTGRES_DB: payment_db
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    ports:
      - "5432:5432"  # Expose to host for debugging only
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paymentuser -d payment_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - payment_network

  # Payment Service (GO)
  payment_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment_service
    restart: unless-stopped
    expose:
      - "8082"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: paymentuser
      DB_PASSWORD: paymentpass
      DB_NAME: payment_db
      DB_SSLMODE: disable
      SERVICE_PORT: 8082
      LOG_LEVEL: info
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - payment_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/health"]
      interval: 30s
      timeout: 3s
      start_period: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  payment_network:
    driver: bridge