version: '3.8'

services:
  # NGINX (API Gateway)
  gateway:
    image: nginx:stable-alpine
    container_name: nginx_gateway
    ports:
      - "8080:80"       
    volumes:
      - ./nginx/:/etc/nginx/
      - ../frontend:/usr/share/nginx/html:ro
    networks:
      - microservices-network
networks:
  microservices-network:
    external: true