version: '3.8'

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik_gateway
    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./dynamic_conf.yml:/dynamic_conf.yml:ro
      - ./acme.json:/acme.json  
      - ../../frontend:/frontend:ro  
    
    ports:
      - "80:80"      
      - "443:443"    
      - "8080:8080"  
    
    environment:
      TRAEFIK_API_DASHBOARD: "true"
      TRAEFIK_GLOBAL_CHECKNEW: "true"
    
    networks:
      - microservices-network
    
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    image: nginx:alpine
    container_name: frontend
    restart: unless-stopped
    volumes:
      - ../../frontend:/usr/share/nginx/html:ro
    networks:
      - microservices-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.frontend.priority=1"

networks:
  microservices-network:
    external: true